@startuml

Title Logging in

State LoggedIn #Khaki

note left of LoggedIn
Username and role
stored in session
end note

[*] -> index

state registration #Wheat {
index #Salmon -> Login #DodgerBlue
Login --> Registration #Salmon
Registration --> RegistrationServlet #DodgerBlue
RegistrationServlet --> Registration : Registration fails
RegistrationServlet --> regSucces #Salmon  : Registration succesfull
}

state userAccess #Wheat {
Login #DodgerBlue --> ShoppingCart #DodgerBlue
regSucces #Salmon --> ShoppingCart
ShoppingCart --> Shop
Shop #Salmon --> ShoppingCart : Add lineitem to shopping cart
Shop -> OrderConfirmation : Place order
OrderConfirmation #DodgerBlue --> Confirmation #Salmon

NavBar #Salmon --> Navigation #DodgerBlue 
Navigation -> index
NavBar --> MyAccount #DodgerBlue
NavBar --> ShoppingCart

}

state adminAccess #Wheat {
NavBar -> Administration #DodgerBlue
Administration --> Admin
Admin #Salmon --> AdminServlet #DodgerBlue : Search orders etc.
}

userAccess --> [*] : Log out
adminAccess --> [*] : Log out

registration --> errorPage #Salmon
userAccess --> errorPage
adminAccess --> errorPage
@enduml