@startuml

Title Logging in

State LoggedIn #Khaki

note left of LoggedIn
Username and role
stored in session
end note

[*] -> index.jsp

state registration #Wheat {

index.jsp #Salmon --> LoginServlet #DodgerBlue
LoginServlet --> Registration.jsp #Salmon
Registration.jsp --> RegistrationServlet #DodgerBlue
RegistrationServlet --> Registration.jsp : Registration fails
RegistrationServlet --> regSucces.jsp #Salmon  : Registration succesfull
}

state userAccess #Wheat {
LoginServlet #DodgerBlue --> ShoppingCart #DodgerBlue
regSucces.jsp #Salmon --> ShoppingCart
ShoppingCart --> Shop.jsp
Shop.jsp #Salmon --> ShoppingCart : Add lineitem to shopping cart
Shop.jsp -> OrderConfirmation : Place order
OrderConfirmation #DodgerBlue --> Confirmation.jsp #Salmon

NavBar #Salmon --> NavServlet #DodgerBlue 
NavServlet --> index.jsp
NavBar --> MyAccountServlet #DodgerBlue
NavBar --> ShoppingCart

}

state adminAccess #Wheat {
NavBar --> AdminServlet #DodgerBlue
AdminServlet --> Admin.jsp 
Admin.jsp #Salmon --> AdminServlet : Search orders etc.
}

userAccess --> [*] : Log out
adminAccess --> [*] : Log out

registration --> errorPage #Salmon
userAccess --> errorPage
adminAccess --> errorPage
@enduml